function params = init_action_params()

alpha   = 2;        % parameter for the geq in constraint
alpha_2   = 0.4;      % parameter for background class constraint
kapa    = 1/10^6;        % penalization for the slack
lambda  = 1e-6;     % regularization constant

params = struct('coordinate', 'actions', ...
                'alpha', alpha, ...
                'alpha_2', alpha_2, ...
                'kapa', kapa, ...
                'n_iter',50000,...
                'lambda', lambda, ...
                'neg_bag', false, ...
                'uniqueness',false, ...
                'cut_crowds', false, ...     % flag to decide whether or not to remove crowded scenes
                'cut_threshold', 30, ...    % max size of crowds in bags
                'opt_flag', 'LINBCFWOPT');  % kind of optimization performed

end
